class TopicModeling:
    def __init__(self, df, column_name, sentence_transformer_model='sentence-transformers/bert-large-nli-stsb-mean-tokens'):
        """
        Initialize the TopicModeling class with the necessary models and data.
        :param df: DataFrame containing the text data.
        :param column_name: Name of the column containing text descriptions.
        :param sentence_transformer_model: Model to be used for sentence embeddings.
        """
        self.df = df
        self.column_name = column_name

        # Use a sentence transformer for embedding
        self.sentence_model = SentenceTransformer(sentence_transformer_model)

        # Set UMAP parameters for better optimization of topic modeling
        self.umap_model = UMAP(
            n_neighbors=30,        # Increased to consider a broader local neighborhood
            n_components=9,        # Reduced dimensionality to capture better topic relationships
            min_dist=0.0,          # Adjusted to allow slight separation between points
            metric="cosine",       # Cosine distance for embedding similarity
            random_state=42,
            low_memory=False
        )

        # Initialize HDBSCAN model for clustering
       # self.hdbscan_model = HDBSCAN(min_samples=5, min_cluster_size=10, metric='euclidean', prediction_data=True)

        # Define seed topics with predefined keywords (IVSA_Order as an example)
        self.seed_topic_list_one = [
            ["ivsa", "ivsa order", "order processing"],    # Custom topic "IVSA_Order"
            ["connect", "connect issue", "connect service"],  # Custom topic "Connect Issues"
            ["server", "server downtime", "server failure"],  # Custom topic "Server Downtime"
            ["healthcheck", "healthcheck workflow", "system check"]  # Custom topic "Healthcheck"
        ]

        # Custom topic names corresponding to the seed topics
        self.custom_topic_names = [
            "IVSA Order Issues",
            "Connect Service Issues",
            "Server Downtime",
            "System Healthcheck"
        ]

        # Initialize BERTopic with HDBSCAN as the clustering model
        self.topic_model = BERTopic(
           # hdbscan_model=self.hdbscan_model,  # Integrating HDBSCAN for clustering
            language="english",
            umap_model=self.umap_model,
            embedding_model=self.sentence_model,
            top_n_words=20,
            n_gram_range=(1, 3),
            calculate_probabilities=True,
            nr_topics=None,  # Allow flexible number of topics
            representation_model=KeyBERTInspired(),
            seed_topic_list=self.seed_topic_list_one  # Use the predefined seed topics
        )

    def encode_embeddings(self):
        """
        Encodes the descriptions into embeddings using the sentence model.
        """
        descriptions = self.df[self.column_name].tolist()
        return self.sentence_model.encode(descriptions, show_progress_bar=False)

    def assign_custom_topic_names(self):
        """
        Assign custom names to topics generated by the BERTopic model.
        """
        # Get the current topic information from the BERTopic model
        topic_info = self.topic_model.get_topic_info()

        # Create a mapping of topic IDs to custom names
        topic_id_to_name = {i: name for i, name in enumerate(self.custom_topic_names)}

        # Replace the default topic names with custom names in topic info
        topic_info['Custom_Topic_Names'] = topic_info['Topic'].map(topic_id_to_name)

        return topic_info

    def fit_topic_model(self, embeddings):
        """
        Fits the BERTopic model using the provided embeddings.
        """
        print(f"Embeddings shape: {np.array(embeddings).shape}")

        try:
            # Fit the BERTopic model using the embeddings and document text
            topics, probabilities = self.topic_model.fit_transform(self.df[self.column_name], embeddings)
        except ValueError as e:
            print(f"Error in fit_transform: {e}")
            raise e

        return topics, probabilities

    def get_similarity_matrix(self, probabilities):
        """
        Computes the cosine similarity matrix from topic probabilities.
        """
        topic_distributions = np.array(probabilities).T  # Transpose to get topics as rows
        return cosine_similarity(topic_distributions)

    def get_topic_info(self):
        """
        Retrieves the topic information from the BERTopic model with custom topic names.
        """
        return self.assign_custom_topic_names()

    def hierarchical_clustering(self, descriptions):
        """
        Performs hierarchical clustering on the topics identified by the BERTopic model.
        """
        linkage_function = lambda x: sch.linkage(x, 'single', optimal_ordering=True)
        return self.topic_model.hierarchical_topics(descriptions, linkage_function=linkage_function)

# Usage
if __name__ == "__main__":
    # Assuming 'df' is your DataFrame and 'consolidated_description' is the column with text data
    topic_modeling = TopicModeling(df, "consolidated_description")

    # Clean the data first to ensure consistency
    topic_modeling.df['consolidated_description'].fillna("", inplace=True)  # Handle NaN with empty strings

    # Encode the embeddings
    embeddings = topic_modeling.encode_embeddings()

    # Fit the topic model and get the assigned topics and probabilities
    topics, probs = topic_modeling.fit_topic_model(embeddings)

    # Print the topic information with custom names
    topic_info = topic_modeling.get_topic_info()
    print(topic_info)
